nelmio_api_doc:
    documentation:
        info:
            title: 'My API'
            description: 'This is a sample API'
            version: '1.0.0'
    areas:
        path_patterns:
            - '^/api'