nelmio_api_doc:
    documentation:
        info:
            title: 'Example API'
            description: 'This is a sample API made for studying purposes'
            version: '1.0.0'
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
    areas:
        path_patterns:
            - '^/api'